workflows:
  doss-ios-testflight-workflow:
    name: DOSS Rider iOS Build and Publish to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      # تأكد أن هذا الاسم هو نفس اسم الـ integration المضاف في حسابك على كودماجيك
      app_store_connect: noourway

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        provisioning_profiles:
          - doss_Manual_Profile
        certificates:
          - ios_cert_manual # تأكد أن هذا هو نفس "الاسم المستعار" (Alias) للشهادة المرفوعة في كودماجيك

    scripts:
      - name: Set iOS deployment target
        script: |
          # رفع إصدار النظام في إعدادات Xcode إلى 14.0
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Clean and Get Dependencies
    script: |
      flutter clean
      flutter pub get

      # إنشاء ملف Podfile بدون طلب شهادات التوثيق لتجنب توقف البناء
      flutter build ios --config-only --no-codesign

      # ضمان تعديل إصدار iOS إلى 14.0 في Podfile سواء كان السطر مفعلاً أو مسبوقاً برمز #
      sed -i '' "s/^# *platform :ios.*/platform :ios, '14.0'/g" ios/Podfile
      sed -i '' "s/^platform :ios.*/platform :ios, '14.0'/g" ios/Podfile

      cd ios
      rm -rf Pods
      rm -rf Podfile.lock
      pod repo update
      pod install

      - name: Apply Vault Profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - codexus.eg@gmail.com
